
class ScriptAgent:
    def __init__(self, task):
        ...

    def evaluate_goal(self, state, goal):
        ...

    def generate_goal(self, state):
        ...

    def generate_skill(self, state, goal):
        ...

    def generate_action(self, skill):
        ...

    def run(self, state):
        ...

if __name__ == '__main__':
    ...
